<?php


/**
 * Implements hook_menupoly()
 */
function menupoly_example_menupoly() {
  return array(
    'main' => array(

      'subject' => t('Main menu (example)'),

      // Tree-building options
      // which menu to fetch items from
      'menu_name' => 'main-menu',
      // root item to constrain the available items
      // 'root_path' => '0',
      // 'root_path' => 'node/1',
      // ??
      'level' => 1,
      // ??
      // 'follow' => MENUPOLY_FOLLOW_CHILDREN,
      'sort' => 0,
      // 'depth' => 2,
      'expand' => MENUPOLY_EXPAND_ALL,
    ),
  );
}


function menupoly_example_menu() {

  return array(
    'admin/structure/menu/menupoly/example' => array(
      'page callback' => 'menupoly_example_page',
      'access arguments' => array('administer site configuration'),
      'title' => 'Menupoly example',
    ),
    'admin/structure/menu/menupoly/example2' => array(
      'page callback' => 'menupoly_example_page_2',
      'access arguments' => array('administer site configuration'),
      'title' => 'Menupoly example 2',
    ),
  );
}


function menupoly_example_page() {
  $config = array(
    // Block options
    'subject' => t('Main menu (example)'),
    'title_link' => 0,
    'admin_title' => '',

    // Tree-building options
    'menu_name' => 'navigation',
    'i18n_menu_name_suffix' => TRUE,
    'expand' => MENUPOLY_EXPAND_ALL,
  );
  return menupoly_view($config);
}


function menupoly_example_page_2() {

  // Typical top-level "flat" menu.
  $variations[] = array(
    'menu_name' => 'main-menu',
    'depth' => 1,
  );

  // Typical second-level "flat" menu.
  $variations[] = array(
    'menu_name' => 'main-menu',
    'level' => 2,
    'depth' => 1,
  );

  // Typical fully expanded dropdown menu.
  $variations[] = array(
    'menu_name' => 'main-menu',
    'expand' => MENUPOLY_EXPAND_ALL,
  );

  // Typical fully expanded dropdown menu with i18n menu selection.
  $variations[] = array(
    'menu_name' => 'menu-test-nav',
    // This will replace the menu name with e.g. menu-test-nav-fr, if you browse
    // in French, and the respective menu exists.
    'i18n_menu_name_suffix' => TRUE,
    'expand' => MENUPOLY_EXPAND_ALL,
  );

  // Dropdown menu for the current sub-section of the site.
  $variations[] = array(
    'menu_name' => 'main-menu',
    'expand' => MENUPOLY_EXPAND_ALL,
    'level' => 2,
  );

  // Typical sidebar menu, where submenus are expanded if
  // - the parent is in the active trail, OR
  // - the parent is marked as "expanded".
  $variations[] = array(
    'menu_name' => 'main-menu',
  );

  // Typical sidebar menu, where submenus are expanded if
  // - the parent is in the active trail.
  $variations[] = array(
    'menu_name' => 'main-menu',
    'expand' => MENUPOLY_EXPAND_ACTIVE,
  );

  // Typical sidebar menu, where submenus are expanded if
  // - the parent is marked as "expanded".
  $variations[] = array(
    'menu_name' => 'main-menu',
    'expand' => MENUPOLY_EXPAND_EXPANDED,
  );

  // Sidebar menu starting at second level.
  $variations[] = array(
    'menu_name' => 'main-menu',
    'level' => 2,
  );

  // Show "children" of the current page.
  $variations[] = array(
    'menu_name' => 'main-menu',
    'follow' => MENUPOLY_FOLLOW_CHILDREN,
    'depth' => 1,
  );

  // Show "siblings" of the current page.
  $variations[] = array(
    'menu_name' => 'main-menu',
    'follow' => MENUPOLY_FOLLOW_SIBLINGS,
    'depth' => 1,
  );

  // Show the submenu tree under 'node/123'
  $variations[] = array(
    'menu_name' => 'main-menu',
    'parent_path' => 'node/123',
  );

  $n = count($variations) - 1;
  $i = (int)@$_GET['variation'];
  $v = $variations[$i];
  $text = t("Choose a number from 0 to $n");
  $pre = print_r($v, TRUE);
  $html = <<<EOT
<form method="GET">
  <p>$text</p>
  <input type="text" class="form-text" name="variation" />
</form>
<code><pre>$pre</pre></code>
EOT;
  return $html . menupoly_view($v);
}





