<?php


/**
 * Implements hook_menupoly()
 */
function menupoly_example_menupoly() {
  return array(
    'main' => array(

      'subject' => t('Main menu (example)'),

      // Tree-building options
      // which menu to fetch items from
      'menu_name' => 'main-menu',
      // root item to constrain the available items
      // 'root_path' => '0',
      // 'root_path' => 'node/1',
      // ??
      'level' => 1,
      // ??
      'follow' => 0,
      'sort' => 0,

      // depth up to which we expand everything.
      // 0 means that nothing is shown.
      // 1 means that only the submenu directly under root is shown.
      // NULL means no depth limit, all submenus under root are expanded.
      // Defaults to 0.
      'depth_all' => 3,

      // depth up to which we expand submenus where the parent is marked as
      // "expanded". 0, 1 and NULL as above for depth_all.
      // Defaults to 0 
      'depth_expanded' => 4,

      // depth up to which we expand streets for seeds.
      // Defaults to 0.
      'depth_street' => 5,

      // minimum depth for items, measured from root.
      // 1: no limit
      // n: the root will be newly determined depending on active trail.
      // Defaults to 1.
      'mindepth' => 0,

      // Legacy depth value. Meaning depends on 'expand' and 'expanded' settings.
      'depth' => 3,
      // Legacy value that combines street depth and pyramid depth.
      'maxdepth' => 5,
      'expanded' => 0,
      'expand' => MENUPOLY_EXPAND_ACTIVE,
    ),
  );
}


function menupoly_example_menu() {

  return array(
    'admin/structure/menu/menupoly/example' => array(
      'page callback' => 'menupoly_example_page',
      'access arguments' => array('administer site configuration'),
      'title' => 'Menupoly example',
    ),
  );
}


function menupoly_example_page() {
  $config = array(
    // Block options
    'subject' => t('Main menu (example)'),
    'title_link' => 0,
    'admin_title' => '',

    // Tree-building options
    // which menu to fetch items from
    'menu_name' => 'main-menu',
    // root item to constrain the available items
    'root_mlid' => '0',
    // 'root_path' => 'some/path',
    // ??
    'level' => 1,
    // ??
    'follow' => 0,
    'sort' => 0,

    // depth up to which we expand everything.
    // 0 means that nothing is shown.
    // 1 means that only the submenu directly under root is shown.
    // NULL means no depth limit, all submenus under root are expanded.
    // Defaults to 0.
    'depth_all' => 3,

    // depth up to which we expand submenus where the parent is marked as
    // "expanded". 0, 1 and NULL as above for depth_all.
    // Defaults to 0 
    'depth_expanded' => 4,

    // depth up to which we expand streets for seeds.
    // Defaults to 0.
    'depth_street' => 5,

    // minimum depth for items, measured from root.
    // 1: no limit
    // n: the root will be newly determined depending on active trail.
    // Defaults to 1.
    'mindepth' => 0,

    // Legacy depth value. Meaning depends on 'expand' and 'expanded' settings.
    'depth' => 3,
    // Legacy value that combines street depth and pyramid depth.
    'maxdepth' => 5,
    'expanded' => 0,
    'expand' => MENUPOLY_EXPAND_ALL,
  );
  return menupoly_view($config);
}


function menupoly_example_page_2() {

  // Typical top-level "flat" menu.
  $config = array(
    'menu_name' => 'main-menu',
    'depth_all' => 1,
  );

  // Typical fully expanded dropdown menu.
  $config = array(
    'menu_name' => 'main-menu',
    'depth_all' => NULL,
  );

  // Dropdown menu for the current sub-section of the site.
  $config = array(
    'menu_name' => 'main-menu',
    'depth_all' => NULL,
    'mindepth' => 2,
  );

  // Typical sidebar menu with submenus for active trail expanded.
  $config = array(
    'menu_name' => 'main-menu',
    'depth_street' => NULL,
  );

  // Sidebar menu starting at a lower level.
  $config = array(
    'menu_name' => 'main-menu',
    'depth_street' => NULL,
    'mindepth' => 2,
  );

  // Show "children" of the current page.
  $config = array(
    'menu_name' => 'main-menu',
    'depth_all' => 1,
    'follow' => TRUE,
  );
}





